# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
#
# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

# Load balancer type. Supported values are: TRAEFIK,NGINX
type: TRAEFIK

# SSL configuration Type. Supported Values are : NONSSL,SSL,E2ESSL
sslType: NONSSL

# domainType. Supported values are: osb,soa,soaosb
domainType: soa

#WLS domain as backend to the load balancer
wlsDomain:
  domainUID: soainfra
  secureEnabled: false
  adminServerName: AdminServer
  adminSecurePort: 9002
  adminServerPort: 7011
  adminServerSSLPort: 7012
  soaClusterName: soa_cluster
  soaManagedServerPort: 8011
  soaManagedServerSSLPort: 8012
  osbClusterName: osb_cluster
  osbManagedServerPort: 9011
  osbManagedServerSSLPort: 9012

# Host  specific values
hostName:
  admin: admin.org
  soa: soa.org
  osb: osb.org
 

# Ngnix specific values
nginx:
  connectTimeout: 1800
  readTimeout: 1800
  sendTimeout: 1800
  cookieExpires: 172800
  cookieMaxAge: 172800


